/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-container": "#576379",
        "secondary": "#535f75",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container": "#e5eeff",
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "secondary-fixed-dim": "#bac7e1",
        "surface-variant": "#d3e4fe",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00174b",
        "primary": "#004ac6",
        "on-secondary-fixed": "#0f1c2f",
        "secondary-container": "#d3e0fa",
        "on-background": "#0b1c30",
        "on-surface-variant": "#434655",
        "inverse-surface": "#213145",
        "on-primary-container": "#eeefff",
        "primary-container": "#2563eb",
        "tertiary": "#006242",
        "secondary-fixed": "#d6e3fd",
        "on-tertiary-fixed": "#002113",
        "tertiary-container": "#007d55",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#3b475c",
        "tertiary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#737686",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "surface-tint": "#0053db",
        "on-tertiary-container": "#bdffdb"
      },
      spacing: {
        gutter: "1rem",
        "gutter-lg": "1.25rem",
        "space-md": "0.75rem",
        "space-xl": "1.25rem",
        "space-lg": "1rem",
        "space-2xl": "1.75rem",
        "space-2xs": "0.25rem",
        "space-sm": "0.5rem",
        margin: "1.25rem",
        "margin-mobile": "0.75rem",
        "space-xs": "0.375rem"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "label-lg": ["Geist", "Inter", "sans-serif"],
        "label-md": ["Geist", "Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "label-sm": ["Geist", "Inter", "sans-serif"],
        "metric-xl": ["Geist", "Inter", "sans-serif"],
        "display-md": ["Geist", "Inter", "sans-serif"],
        "metric-lg": ["Geist", "Inter", "sans-serif"],
        "headline-sm": ["Geist", "Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "metric-xl": ["26px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "metric-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["15px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
